unit TestStringHelpers;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework;

type
  // Test methods for class TCrypt

  TTestStringHelpers = class(TTestCase)
  strict private

  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TesteIsValidCelular;
  end;

implementation

uses Helpers.HelperString;

{ TestStringHelpers }
procedure TTestStringHelpers.SetUp;
begin
  inherited;

end;

procedure TTestStringHelpers.TearDown;
begin
  inherited;

end;

procedure TTestStringHelpers.TesteIsValidCelular;
begin
  Assert('11998765432'.IsValidCelular, 'Teste falhou. O número de celular válido foi considerado inválido.');
  Assert(not'55119987654321'.IsValidCelular, 'Teste falhou. O número de celular com mais de 11 dígitos foi considerado válido.');
  Assert(not'5511998765'.IsValidCelular, 'Teste falhou. O número de celular com menos de 11 dígitos foi considerado válido.');
  Assert(not'5511554321'.IsValidCelular, 'Teste falhou. O número de celular inválido foi considerado válido.');
  Assert(not'5511ABC9876'.IsValidCelular, 'Teste falhou. O número de celular com formato inválido foi considerado válido.');

end;

initialization

// Register any test cases with the test runner
RegisterTest(TTestStringHelpers.Suite);

end.
