unit TestDao;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Model.ModelBase, Dao.Base, System.Classes,
  Dao.Conection, Data.DB, System.Rtti, Dao.Conection.Parametros, Database.SGDB, Test.Model.Produto;

type
  // Test methods for class TDaoBase

  TestTDaoBase = class(TTestCase)
  strict private
    FDaoBase: TDaoBase<TProduto>;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTDaoBase.SetUp;
var
  conexao: TConection;

begin
  conexao := TConection.Create(
    TConectionParametros.Create(
    tpSqlServer,
    'LOCALHOST',
    'PDV_PC2',
    'rm',
    'rm',
    'Teste',
    0
    )
    );

  FDaoBase := TDaoBase<TProduto>.Create(conexao);
  FDaoBase.Salvar();
end;

procedure TestTDaoBase.TearDown;
begin
  FDaoBase.Free;
  FDaoBase := nil;
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTDaoBase.Suite);

end.
